-- =====================================================
-- PROJECT L
-- THE NIGHT THE LIBRARY OPENED
-- MEMORY FOUNDATION
-- =====================================================

create table if not exists raw_catchall (

    id bigint generated by default as identity primary key,

    created_at timestamptz default now(),

    role text,

    source text,

    content text,

    conversation_id text,

    metadata jsonb default '{}'::jsonb

);

create table if not exists identity_anchors (

    id bigint generated by default as identity primary key,

    created_at timestamptz default now(),

    key text,

    value text,

    confidence numeric default 1.0,

    source_reference bigint

);

create table if not exists episodic_memories (

    id bigint generated by default as identity primary key,

    created_at timestamptz default now(),

    event_date text,

    category text,

    summary text,

    confidence numeric default 1.0,

    source_reference bigint,

    metadata jsonb default '{}'::jsonb

);

create table if not exists emotional_reflections (

    id bigint generated by default as identity primary key,

    created_at timestamptz default now(),

    emotion text,

    reflection text,

    confidence numeric default 0.5,

    source_reference bigint,

    metadata jsonb default '{}'::jsonb

);

create table if not exists structured_summaries (

    id bigint generated by default as identity primary key,

    created_at timestamptz default now(),

    category text,

    summary text,

    confidence numeric default 0.7,

    source_reference bigint,

    metadata jsonb default '{}'::jsonb

);
