-- =====================================================
-- PROJECT L — RAW CATCHALL MEMORY TABLE
-- Run this once inside Supabase SQL Editor
-- =====================================================

create table if not exists raw_catchall (
    id bigint generated by default as identity primary key,
    timestamp text,
    source text,
    role text,
    content text,
    created_at timestamptz default now()
);

create index if not exists raw_catchall_created_at_idx
on raw_catchall(created_at);

create index if not exists raw_catchall_role_idx
on raw_catchall(role);
